Traceback (most recent call last):
  File "/home/shivam/Desktop/side_quests/generalisation_project/OKG/frameworks/GPT4/streamlined_for_experiments/for_knowledge_expansion_2/./LLM_only/final_run.py", line 5, in <module>
    put_down_obj("sugar", "countertop")
  File "/home/shivam/Desktop/side_quests/generalisation_project/OKG/frameworks/GPT4/streamlined_for_experiments/for_knowledge_expansion_2/LLM_only/functions/actions.py", line 442, in put_down_obj
    raise RuntimeError(f"put_down_obj({obj}, {loc}) #{obj} not present in the environment!")
RuntimeError: put_down_obj(sugar, countertop) #sugar not present in the environment!
