Traceback (most recent call last):
  File "/home/shivam/Desktop/side_quests/generalisation_project/OKG/frameworks/GPT4/other_domains/for_knowledge_expansion_2/./LLM_only/final_run.py", line 3, in <module>
    put_down_rec("charging_pod", "table")
  File "/home/shivam/Desktop/side_quests/generalisation_project/OKG/frameworks/GPT4/other_domains/for_knowledge_expansion_2/LLM_only/functions/actions.py", line 909, in put_down_rec
    raise RuntimeError(f"put_down_rec({rec}, {loc}) #couldnt pick {rec}! It is big")
RuntimeError: put_down_rec(charging_pod, table) #couldnt pick charging_pod! It is big
